/**
 * Integration tests for v0.9 multi-ecosystem commands:
 * better migrate (all ecosystems), better plugin, offline mode,
 * cross-ecosystem monorepo, registry failover
 */
import test from "node:test";
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs/promises";
import path from "node:path";
import { makeTempDir, rmrf, writeJson } from "./helpers.js";

const execFileAsync = promisify(execFile);
const betterBin = path.resolve(process.cwd(), "bin", "better.js");

async function runBetter(args, cwd) {
  return execFileAsync("node", [betterBin, ...args], {
    cwd: cwd || process.cwd(),
    env: { ...process.env, NO_COLOR: "1" },
    timeout: 20000,
  }).catch(err => ({ stdout: err.stdout || "", stderr: err.stderr || "", code: err.code }));
}

// ── better migrate ────────────────────────────────────────────────────────────

test("better migrate --help shows usage", async () => {
  const result = await runBetter(["migrate", "--help"]);
  assert.ok(
    result.stdout.includes("migrate") || result.stdout.includes("lock"),
    `Expected migrate help, got: ${result.stdout}`
  );
});

test("better migrate --json in a non-npm project returns structured output", async () => {
  const dir = await makeTempDir("better-migrate-");
  try {
    // Simulate a Cargo project
    await fs.writeFile(
      path.join(dir, "Cargo.toml"),
      '[package]\nname = "test-crate"\nversion = "0.1.0"\nedition = "2021"\n'
    );
    const result = await runBetter(["migrate", "--json"], dir);
    if (result.stdout && result.stdout.trim().startsWith("{")) {
      const parsed = JSON.parse(result.stdout.trim());
      assert.ok(typeof parsed === "object", "Expected JSON object");
    } else {
      // May fail gracefully if no source lockfile
      assert.ok(result.stdout.length > 0 || result.stderr.length > 0 || result.code !== 0);
    }
  } finally {
    await rmrf(dir);
  }
});

test("better migrate detects npm project type", async () => {
  const dir = await makeTempDir("better-migrate-npm-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-pkg", version: "1.0.0", dependencies: {}
    });
    // Create a yarn.lock
    await fs.writeFile(path.join(dir, "yarn.lock"), "# THIS IS AN AUTOGENERATED FILE.\n");
    const result = await runBetter(["migrate", "--json", "--from", "yarn"], dir);
    if (result.stdout && result.stdout.trim().startsWith("{")) {
      const parsed = JSON.parse(result.stdout.trim());
      assert.ok(typeof parsed === "object");
    } else {
      assert.ok(result.stdout.length > 0 || result.code !== 0);
    }
  } finally {
    await rmrf(dir);
  }
});

// ── better plugin ─────────────────────────────────────────────────────────────

test("better plugin --help shows usage", async () => {
  const result = await runBetter(["plugin", "--help"]);
  assert.ok(
    result.stdout.includes("plugin") || result.stdout.includes("wasm"),
    `Expected plugin help, got: ${result.stdout}`
  );
});

test("better plugin list --json returns structured output", async () => {
  const result = await runBetter(["plugin", "list", "--json"]);
  if (result.stdout && result.stdout.trim().startsWith("{")) {
    const parsed = JSON.parse(result.stdout.trim());
    assert.ok(typeof parsed === "object", "Expected JSON object");
  } else if (result.stdout && result.stdout.trim().startsWith("[")) {
    const parsed = JSON.parse(result.stdout.trim());
    assert.ok(Array.isArray(parsed), "Expected JSON array");
  } else {
    assert.ok(result.stdout.length > 0 || result.code !== 0);
  }
});

// ── better install --offline ───────────────────────────────────────────────────

test("better install --offline --help shows offline flag", async () => {
  const result = await runBetter(["install", "--help"]);
  assert.ok(
    result.stdout.includes("install") || result.stdout.includes("offline") ||
    result.stdout.includes("Install"),
    `Expected install help with offline flag, got: ${result.stdout}`
  );
});

// ── cross-ecosystem doctor ────────────────────────────────────────────────────

test("better doctor --help shows usage", async () => {
  const result = await runBetter(["doctor", "--help"]);
  assert.ok(
    result.stdout.includes("doctor") || result.stdout.includes("health"),
    `Expected doctor help, got: ${result.stdout}`
  );
});

test("better doctor --json returns structured output", async () => {
  const dir = await makeTempDir("better-doctor-eco-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project", version: "1.0.0", dependencies: {}
    });
    const result = await runBetter(["doctor", "--json"], dir);
    if (result.stdout && result.stdout.trim().startsWith("{")) {
      const parsed = JSON.parse(result.stdout.trim());
      assert.ok(parsed.kind !== undefined || parsed.ok !== undefined || parsed.checks !== undefined,
        `Expected structured doctor output, got: ${JSON.stringify(parsed)}`);
    } else {
      // Doctor may print text output
      assert.ok(result.stdout.length > 0 || result.stderr.length > 0);
    }
  } finally {
    await rmrf(dir);
  }
});

// ── registry failover ─────────────────────────────────────────────────────────

test("better registry --help shows usage", async () => {
  const result = await runBetter(["registry", "--help"]);
  assert.ok(
    result.stdout.includes("registry") || result.stdout.includes("Registry"),
    `Expected registry help, got: ${result.stdout}`
  );
});

test("better registry list --json returns structured output", async () => {
  const result = await runBetter(["registry", "list", "--json"]);
  if (result.stdout && result.stdout.trim().startsWith("{")) {
    const parsed = JSON.parse(result.stdout.trim());
    assert.ok(typeof parsed === "object");
  } else if (result.stdout && result.stdout.trim().startsWith("[")) {
    const parsed = JSON.parse(result.stdout.trim());
    assert.ok(Array.isArray(parsed));
  } else {
    assert.ok(result.stdout.length > 0 || result.code !== 0);
  }
});

// ── cross-ecosystem stats ─────────────────────────────────────────────────────

test("better stats --help shows usage", async () => {
  const result = await runBetter(["stats", "--help"]);
  assert.ok(
    result.stdout.includes("stats") || result.stdout.includes("cache"),
    `Expected stats help, got: ${result.stdout}`
  );
});

test("better stats --json returns structured output", async () => {
  const result = await runBetter(["stats", "--json"]);
  if (result.stdout && result.stdout.trim().startsWith("{")) {
    const parsed = JSON.parse(result.stdout.trim());
    assert.ok(typeof parsed === "object", "Expected JSON stats object");
  } else {
    assert.ok(result.stdout.length > 0 || result.code !== 0);
  }
});

// ── Task 73: better env generate (cross-ecosystem) ───────────────────────────

test("better env generate --help shows usage", async () => {
  const result = await runBetter(["env", "generate", "--help"]);
  assert.ok(
    result.stdout.includes("env") || result.stdout.includes("generate") || result.stdout.includes(".env"),
    `Expected env generate help, got: ${result.stdout}`
  );
});

test("better env generate in empty dir returns error or help", async () => {
  const dir = await makeTempDir();
  try {
    const result = await runBetter(["env", "generate"], dir);
    // Without .env.osp, should produce an error
    assert.ok(
      result.code !== 0 || result.stdout.includes("error") || result.stderr.includes("error")
        || result.stdout.includes(".env.osp") || result.stderr.includes(".env.osp"),
      `Expected error about missing .env.osp, got stdout=${result.stdout} stderr=${result.stderr}`
    );
  } finally {
    await rmrf(dir);
  }
});

test("better env generate with plain .env.osp writes .env", async () => {
  const dir = await makeTempDir();
  try {
    // Write a template with no osp:// URIs — just plain values
    await fs.writeFile(path.join(dir, ".env.osp"), "APP_NAME=myapp\nDEBUG=true\n");
    const result = await runBetter(["env", "generate"], dir);
    // Either succeeds and writes .env, or errors due to missing vault (acceptable)
    const hasEnv = await fs.access(path.join(dir, ".env")).then(() => true).catch(() => false);
    const hasEnvLocal = await fs.access(path.join(dir, ".env.local")).then(() => true).catch(() => false);
    // If the command succeeded, either .env or .env.local should exist
    if (result.code === 0) {
      assert.ok(hasEnv || hasEnvLocal, "Expected .env or .env.local to be written on success");
    }
    // If command failed (vault not open etc), that's acceptable in CI
    assert.ok(result.stdout !== undefined);
  } finally {
    await rmrf(dir);
  }
});

// ── Task 74: better migrate (all ecosystems) ─────────────────────────────────

test("better migrate --list shows detected lockfiles in temp dir", async () => {
  const dir = await makeTempDir();
  try {
    await fs.writeFile(path.join(dir, "package-lock.json"), JSON.stringify({
      lockfileVersion: 3, packages: {}, dependencies: {}
    }));
    const result = await runBetter(["migrate", "--list"], dir);
    assert.ok(
      result.stdout.includes("package-lock") || result.stdout.includes("npm")
        || result.stdout.length > 0 || result.code !== 0,
      "Expected migrate --list to show detected lockfiles"
    );
  } finally {
    await rmrf(dir);
  }
});

test("better migrate --from cargo --help shows usage", async () => {
  const result = await runBetter(["migrate", "--from", "cargo", "--help"]);
  assert.ok(
    result.stdout.includes("migrate") || result.stdout.includes("cargo")
      || result.stdout.includes("Cargo"),
    `Expected cargo migration help, got: ${result.stdout}`
  );
});

test("better migrate --from go --help shows usage", async () => {
  const result = await runBetter(["migrate", "--from", "go", "--help"]);
  assert.ok(
    result.stdout.includes("migrate") || result.stdout.includes("go")
      || result.stdout.includes("go.sum"),
    `Expected go migration help, got: ${result.stdout}`
  );
});

test("better migrate in polyglot temp dir detects multiple ecosystems", async () => {
  const dir = await makeTempDir();
  try {
    // Create fake lockfiles
    await fs.writeFile(path.join(dir, "package-lock.json"), "{}");
    await fs.writeFile(path.join(dir, "go.sum"), "");
    const result = await runBetter(["migrate", "--list", "--json"], dir);
    if (result.stdout && result.stdout.trim().startsWith("[")) {
      const parsed = JSON.parse(result.stdout.trim());
      assert.ok(Array.isArray(parsed));
    } else if (result.stdout && result.stdout.trim().startsWith("{")) {
      const parsed = JSON.parse(result.stdout.trim());
      assert.ok(typeof parsed === "object");
    } else {
      assert.ok(result.stdout.length > 0 || result.code !== 0);
    }
  } finally {
    await rmrf(dir);
  }
});
