import test from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { makeTempDir, rmrf, writeJson, writeFile } from "./helpers.js";
import { verifyFrozenLockfile } from "../src/lib/frozenLockfile.js";
import { loadOverrides, validateOverrides, suggestOverridesForVulns } from "../src/lib/overrides.js";

// ── Frozen lockfile tests ──────────────────────────────────────────────

test("frozenLockfile: passes when lockfile matches package.json", async () => {
  const dir = await makeTempDir("frozen-pass-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project",
      version: "1.0.0",
      dependencies: { lodash: "^4.17.21" }
    });
    await writeJson(path.join(dir, "package-lock.json"), {
      name: "test-project",
      lockfileVersion: 3,
      packages: {
        "": { name: "test-project", version: "1.0.0", dependencies: { lodash: "^4.17.21" } },
        "node_modules/lodash": { version: "4.17.21", resolved: "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz" }
      }
    });

    const result = await verifyFrozenLockfile(dir, { pm: "npm" });
    assert.equal(result.ok, true);
    assert.equal(result.errors.length, 0);
    assert.equal(result.lockfile, "package-lock.json");
    assert.equal(result.hash.length, 64);
  } finally {
    await rmrf(dir);
  }
});

test("frozenLockfile: fails when lockfile is missing", async () => {
  const dir = await makeTempDir("frozen-missing-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project",
      version: "1.0.0"
    });

    const result = await verifyFrozenLockfile(dir, { pm: "npm" });
    assert.equal(result.ok, false);
    assert.ok(result.errors.length > 0);
    assert.ok(result.errors[0].includes("No lockfile found"));
  } finally {
    await rmrf(dir);
  }
});

test("frozenLockfile: fails when dependency missing from lockfile", async () => {
  const dir = await makeTempDir("frozen-mismatch-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project",
      version: "1.0.0",
      dependencies: { lodash: "^4.17.21", express: "^4.18.0" }
    });
    await writeJson(path.join(dir, "package-lock.json"), {
      name: "test-project",
      lockfileVersion: 3,
      packages: {
        "": { name: "test-project", version: "1.0.0" },
        "node_modules/lodash": { version: "4.17.21" }
        // express is missing!
      }
    });

    const result = await verifyFrozenLockfile(dir, { pm: "npm" });
    assert.equal(result.ok, false);
    assert.ok(result.errors.some(e => e.includes("express")));
  } finally {
    await rmrf(dir);
  }
});

test("frozenLockfile: warns on old lockfile version", async () => {
  const dir = await makeTempDir("frozen-old-lock-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project",
      version: "1.0.0"
    });
    await writeJson(path.join(dir, "package-lock.json"), {
      name: "test-project",
      lockfileVersion: 1,
      packages: {
        "": { name: "test-project", version: "1.0.0" }
      }
    });

    const result = await verifyFrozenLockfile(dir, { pm: "npm" });
    assert.equal(result.ok, true);
    assert.ok(result.warnings.some(w => w.includes("outdated")));
  } finally {
    await rmrf(dir);
  }
});

test("frozenLockfile: works with yarn.lock", async () => {
  const dir = await makeTempDir("frozen-yarn-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project",
      version: "1.0.0",
      dependencies: { lodash: "^4.17.21" }
    });
    await writeFile(
      path.join(dir, "yarn.lock"),
      [
        "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
        "# yarn lockfile v1",
        "",
        "lodash@^4.17.21:",
        '  version "4.17.21"',
        '  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"',
        ""
      ].join("\n")
    );

    const result = await verifyFrozenLockfile(dir, { pm: "yarn" });
    assert.equal(result.ok, true);
    assert.equal(result.lockfile, "yarn.lock");
    assert.equal(result.type, "yarn");
  } finally {
    await rmrf(dir);
  }
});

test("frozenLockfile: fails when package missing from yarn.lock", async () => {
  const dir = await makeTempDir("frozen-yarn-miss-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project",
      version: "1.0.0",
      dependencies: { lodash: "^4.17.21", express: "^4.18.0" }
    });
    await writeFile(
      path.join(dir, "yarn.lock"),
      [
        "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
        "# yarn lockfile v1",
        "",
        "lodash@^4.17.21:",
        '  version "4.17.21"',
        ""
      ].join("\n")
    );

    const result = await verifyFrozenLockfile(dir, { pm: "yarn" });
    assert.equal(result.ok, false);
    assert.ok(result.errors.some(e => e.includes("express")));
  } finally {
    await rmrf(dir);
  }
});

// ── Overrides tests ────────────────────────────────────────────────────

test("overrides: loads npm overrides from package.json", async () => {
  const dir = await makeTempDir("overrides-npm-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project",
      version: "1.0.0",
      overrides: {
        lodash: "4.17.21",
        "semver": "7.5.4"
      }
    });

    const result = await loadOverrides(dir);
    assert.equal(result.ok, true);
    assert.equal(result.format, "npm");
    assert.equal(result.count, 2);
    assert.ok(result.flat.some(f => f.pattern === "lodash" && f.version === "4.17.21"));
  } finally {
    await rmrf(dir);
  }
});

test("overrides: loads yarn resolutions from package.json", async () => {
  const dir = await makeTempDir("overrides-yarn-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project",
      version: "1.0.0",
      resolutions: {
        "lodash": "4.17.21",
        "**/minimist": "1.2.8"
      }
    });

    const result = await loadOverrides(dir);
    assert.equal(result.ok, true);
    assert.equal(result.format, "yarn");
    assert.equal(result.count, 2);
  } finally {
    await rmrf(dir);
  }
});

test("overrides: loads pnpm overrides from package.json", async () => {
  const dir = await makeTempDir("overrides-pnpm-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project",
      version: "1.0.0",
      pnpm: {
        overrides: {
          "glob-parent": ">=5.1.2"
        }
      }
    });

    const result = await loadOverrides(dir);
    assert.equal(result.ok, true);
    assert.equal(result.format, "pnpm");
    assert.equal(result.count, 1);
  } finally {
    await rmrf(dir);
  }
});

test("overrides: returns empty when no overrides present", async () => {
  const dir = await makeTempDir("overrides-none-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project",
      version: "1.0.0"
    });

    const result = await loadOverrides(dir);
    assert.equal(result.ok, true);
    assert.equal(result.count, 0);
    assert.equal(result.format, null);
  } finally {
    await rmrf(dir);
  }
});

test("overrides: validates overrides against lockfile", () => {
  const flatOverrides = [
    { pattern: "lodash", version: "4.17.21", source: "overrides" },
    { pattern: "express", version: "4.18.2", source: "overrides" },
    { pattern: "missing-pkg", version: "1.0.0", source: "overrides" }
  ];

  const lockPackages = {
    "node_modules/lodash": { version: "4.17.21" },
    "node_modules/express": { version: "4.18.3" }
    // missing-pkg not in lockfile
  };

  const result = validateOverrides(flatOverrides, lockPackages);
  assert.equal(result.valid.length, 1); // lodash matches
  assert.equal(result.warnings.length, 2); // express version mismatch + missing-pkg
  assert.ok(result.valid[0].package === "lodash");
  assert.ok(result.warnings.some(w => w.issue === "version_mismatch"));
  assert.ok(result.warnings.some(w => w.issue === "package_not_in_lockfile"));
});

test("overrides: flattens nested npm overrides", async () => {
  const dir = await makeTempDir("overrides-nested-");
  try {
    await writeJson(path.join(dir, "package.json"), {
      name: "test-project",
      version: "1.0.0",
      overrides: {
        "express": {
          "debug": "4.3.5"
        },
        "lodash": "4.17.21"
      }
    });

    const result = await loadOverrides(dir);
    assert.equal(result.ok, true);
    assert.equal(result.format, "npm");
    assert.ok(result.flat.some(f => f.pattern.includes("express > debug")));
    assert.ok(result.flat.some(f => f.pattern === "lodash"));
  } finally {
    await rmrf(dir);
  }
});

test("overrides: suggestOverridesForVulns generates suggestions", () => {
  const vulnNodes = [
    {
      name: "lodash",
      version: "4.17.19",
      vulns: [
        {
          id: "GHSA-1234",
          summary: "Prototype Pollution",
          ranges: [{ fixed: "4.17.21" }]
        }
      ]
    },
    {
      name: "minimist",
      version: "1.2.5",
      vulns: [
        {
          id: "GHSA-5678",
          summary: "Prototype Pollution",
          ranges: [{ fixed: "1.2.6" }, { fixed: "1.2.8" }]
        }
      ]
    }
  ];

  const suggestions = suggestOverridesForVulns(vulnNodes, "npm");
  assert.equal(suggestions.lodash, "4.17.21");
  assert.equal(suggestions.minimist, "1.2.8"); // highest fixed version
});
