use super::*;

/// Render a PackageContext into a markdown document optimized for LLM context windows.
pub fn render_context(ctx: &PackageContext) -> String {
    let mut md = String::with_capacity(4096);

    // Header
    md.push_str(&format!("# {}@{}\n\n", ctx.name, ctx.version));

    if !ctx.description.is_empty() {
        md.push_str(&ctx.description);
        md.push_str("\n\n");
    }

    md.push_str(&format!("**Ecosystem:** {}\n\n", ctx.ecosystem));

    // Exports
    if !ctx.exports.is_empty() {
        md.push_str("## Exports\n\n");
        for sym in &ctx.exports {
            if let Some(ref sig) = sym.signature {
                md.push_str(&format!("- `{}`", sig));
            } else {
                md.push_str(&format!("- {} `{}`", sym.kind, sym.name));
            }
            if let Some(ref desc) = sym.description {
                md.push_str(&format!(" -- {}", desc));
            }
            md.push('\n');
        }
        md.push('\n');
    }

    // Types Summary
    if let Some(ref types) = ctx.types_summary {
        md.push_str("## Types Summary\n\n");
        md.push_str(types);
        md.push('\n');
    }

    // Quick Start
    if !ctx.quick_start.is_empty() {
        let lang = if ctx.ecosystem == "python" {
            "python"
        } else {
            "javascript"
        };
        md.push_str("## Quick Start\n\n");
        md.push_str(&format!("```{}\n", lang));
        md.push_str(&ctx.quick_start);
        md.push_str("\n```\n\n");
    }

    // Common Patterns
    if !ctx.patterns.is_empty() {
        md.push_str("## Common Patterns\n\n");
        for pattern in &ctx.patterns {
            md.push_str(&format!("### {}\n\n", pattern.title));
            md.push_str(&format!("```{}\n", pattern.language));
            md.push_str(&pattern.code);
            md.push_str("\n```\n\n");
        }
    }

    // Gotchas / Breaking Changes
    if !ctx.gotchas.is_empty() {
        md.push_str("## Gotchas / Breaking Changes\n\n");
        for gotcha in &ctx.gotchas {
            md.push_str(&format!("- {}\n", gotcha));
        }
        md.push('\n');
    }

    // Dependencies
    if !ctx.dependencies.is_empty() {
        md.push_str("## Dependencies\n\n");
        for dep in &ctx.dependencies {
            md.push_str(&format!("- `{}`\n", dep));
        }
        md.push('\n');
    }

    md.push_str(&format!(
        "---\n*Generated by better v{} at {}*\n",
        crate::VERSION,
        ctx.generated_at
    ));

    md
}
