/**
 * better gen-types — generate TypeScript type stubs for untyped packages
 *
 * For packages that don't have @types/* coverage and don't bundle types,
 * generates minimal .d.ts declaration files so TypeScript won't error.
 *
 * Usage:
 *   better gen-types
 *   better gen-types lodash underscore
 *   better gen-types --output types/
 */
import { parseArgs } from "node:util";
import { printJson, printText } from "../lib/output.js";
import { getRuntimeConfig } from "../lib/config.js";
import fs from "node:fs/promises";
import path from "node:path";
import https from "node:https";
import { resolveInstallProjectRoot } from "../lib/projectRoot.js";

function checkTypesPackage(name) {
  return new Promise((resolve) => {
    const typesName = `@types/${name.replace(/^@/, "").replace("/", "__")}`;
    const encoded = encodeURIComponent(typesName).replace(/%40/g, "@");
    https.get(`https://registry.npmjs.org/${encoded}/latest`, {
      headers: { "Accept": "application/json", "User-Agent": "better-npm/0.1" },
      timeout: 4000,
    }, (res) => {
      let body = "";
      res.on("data", c => { body += c; });
      res.on("end", () => {
        try {
          const data = JSON.parse(body);
          resolve(data.version ? typesName : null);
        } catch { resolve(null); }
      });
    }).on("error", () => resolve(null)).on("timeout", () => resolve(null));
  });
}

async function hasBundledTypes(nmPath, name) {
  try {
    const pkg = JSON.parse(await fs.readFile(path.join(nmPath, name, "package.json"), "utf8"));
    if (pkg.types || pkg.typings) return true;
    if (pkg.exports) {
      const exportStr = JSON.stringify(pkg.exports);
      if (exportStr.includes(".d.ts")) return true;
    }
    // Check for index.d.ts
    try {
      await fs.access(path.join(nmPath, name, "index.d.ts"));
      return true;
    } catch {}
  } catch {}
  return false;
}

function generateDts(name, pkg) {
  const exports = pkg?.main ? "module exports" : "unknown structure";
  const safeName = name.replace(/[@/]/g, "_").replace(/-/g, "_");

  return `// Auto-generated type stub for "${name}"
// Generated by better gen-types — replace with proper types when available

declare module "${name}" {
  // TODO: Add proper type declarations
  // This is a minimal stub to prevent TypeScript errors
  const ${safeName}: any;
  export = ${safeName};
}
`;
}

export async function cmdGenTypes(argv) {
  const runtime = getRuntimeConfig();
  const { values, positionals } = parseArgs({
    args: argv,
    options: {
      json:    { type: "boolean", default: runtime.json === true },
      help:    { type: "boolean", short: "h", default: false },
      output:  { type: "string", default: "types" },
      force:   { type: "boolean", default: false },
      "dry-run": { type: "boolean", default: false },
    },
    allowPositionals: true,
    strict: false,
  });

  if (values.help) {
    printText(`Usage: better gen-types [packages...] [options]

Generate TypeScript declaration stubs for untyped packages.

Options:
  --output <dir>   Output directory for .d.ts files (default: types/)
  --force          Overwrite existing stubs
  --dry-run        Preview what would be generated
  --json           Machine-readable output
  -h, --help       Show this help

Examples:
  better gen-types
  better gen-types lodash my-legacy-module
  better gen-types --output src/types
`);
    return;
  }

  const cwd = process.cwd();
  const resolvedRoot = await resolveInstallProjectRoot(cwd);
  const projectRoot = resolvedRoot.root;

  let pkgJson;
  try {
    pkgJson = JSON.parse(await fs.readFile(path.join(projectRoot, "package.json"), "utf8"));
  } catch {
    const msg = "Cannot read package.json";
    if (values.json) { printJson({ ok: false, error: msg }); } else { printText(`Error: ${msg}`); }
    process.exitCode = 1;
    return;
  }

  const nmPath = path.join(projectRoot, "node_modules");
  const targets = positionals.length > 0
    ? positionals
    : Object.keys(pkgJson.dependencies || {});

  if (!values.json) {
    process.stderr.write(`\x1b[90mChecking types for ${targets.length} package(s)…\x1b[0m\n`);
  }

  const BATCH = 8;
  const needsStub = [];

  for (let i = 0; i < targets.length; i += BATCH) {
    const batch = targets.slice(i, i + BATCH);
    const results = await Promise.all(batch.map(async (name) => {
      // Check bundled types
      const bundled = await hasBundledTypes(nmPath, name);
      if (bundled) return { name, skip: "has bundled types" };

      // Check @types/* on registry
      const typesPackage = await checkTypesPackage(name);
      if (typesPackage) return { name, skip: `use: npm i -D ${typesPackage}`, typesPackage };

      // Needs stub
      let pkg = null;
      try { pkg = JSON.parse(await fs.readFile(path.join(nmPath, name, "package.json"), "utf8")); } catch {}

      return { name, needsStub: true, pkg };
    }));
    needsStub.push(...results);
  }

  const toGenerate = needsStub.filter(r => r.needsStub);
  const hasTypes = needsStub.filter(r => r.skip?.startsWith("has "));
  const hasTypesPackage = needsStub.filter(r => r.typesPackage);

  if (values.json) {
    printJson({
      ok: true,
      kind: "better.gen-types",
      totalChecked: targets.length,
      hasBundledTypes: hasTypes.length,
      hasTypesPackage: hasTypesPackage.length,
      needsStub: toGenerate.length,
      packages: needsStub,
    });
    return;
  }

  printText(`\n\x1b[1mbetter gen-types\x1b[0m — ${targets.length} packages checked\n`);

  if (hasTypesPackage.length > 0) {
    printText(`\x1b[33m${hasTypesPackage.length} package(s) have @types/* available:\x1b[0m`);
    for (const r of hasTypesPackage) {
      printText(`  \x1b[33m→\x1b[0m  ${r.name}  \x1b[90m${r.skip}\x1b[0m`);
    }
    printText("");
  }

  if (toGenerate.length === 0) {
    printText(`\x1b[32m✔ No stub generation needed — all packages have type coverage.\x1b[0m`);
    return;
  }

  const outputDir = path.isAbsolute(values.output)
    ? values.output
    : path.join(projectRoot, values.output);

  if (!values["dry-run"]) {
    await fs.mkdir(outputDir, { recursive: true });
  }

  printText(`Generating stubs in \x1b[1m${path.relative(process.cwd(), outputDir)}/\x1b[0m\n`);

  const generated = [];
  for (const r of toGenerate) {
    const safeName = r.name.replace(/[@/]/g, "_").replace(/-/g, "_");
    const filename = `${safeName}.d.ts`;
    const outPath = path.join(outputDir, filename);

    let exists = false;
    try { await fs.access(outPath); exists = true; } catch {}

    if (exists && !values.force) {
      printText(`  \x1b[90m·\x1b[0m  ${r.name}  \x1b[90m(${filename} already exists, use --force to overwrite)\x1b[0m`);
      continue;
    }

    const content = generateDts(r.name, r.pkg);

    if (!values["dry-run"]) {
      await fs.writeFile(outPath, content, "utf8");
    }

    printText(`  \x1b[32m✔\x1b[0m  ${r.name}  → \x1b[90m${filename}\x1b[0m`);
    generated.push({ name: r.name, file: filename });
  }

  printText("");
  if (values["dry-run"]) {
    printText(`\x1b[90mDry-run: ${generated.length} stubs would be generated. Run without --dry-run to create.\x1b[0m`);
  } else {
    printText(`\x1b[32m✔ Generated ${generated.length} stub(s).\x1b[0m`);
    if (generated.length > 0) {
      printText(`\n\x1b[90mAdd to tsconfig.json:\x1b[0m`);
      printText(`\x1b[90m  "typeRoots": ["./${path.relative(projectRoot, outputDir)}", "node_modules/@types"]\x1b[0m`);
    }
  }
  printText("");
}
