use std::path::Path;

use super::credentials;
use super::discovery::OspError;
use super::vault::Vault;

/// Parse a .env.osp template and resolve osp:// URIs from the vault.
/// Returns resolved key=value pairs ready to write to .env.
pub fn generate_env(
    template_path: &Path,
    vault: &Vault,
    agent_secret_key: &[u8; 32],
) -> Result<Vec<(String, String)>, OspError> {
    let content = std::fs::read_to_string(template_path)
        .map_err(|e| OspError::VaultError(format!("Cannot read {}: {}", template_path.display(), e)))?;

    let mut result = Vec::new();
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = trimmed.split_once('=') {
            let key = key.trim().to_string();
            let value = value.trim().to_string();
            if value.starts_with("osp://") {
                let resolved = credentials::resolve_osp_uri(&value, vault, agent_secret_key)?;
                result.push((key, resolved));
            } else {
                result.push((key, value));
            }
        }
    }
    Ok(result)
}

/// Write resolved env pairs to a .env file.
pub fn write_env_file(
    output_path: &Path,
    pairs: &[(String, String)],
) -> Result<(), OspError> {
    let mut content = String::new();
    content.push_str("# Generated by better env generate\n");
    content.push_str("# Do not commit this file\n\n");
    for (key, value) in pairs {
        // Quote values that contain spaces or special chars
        if value.contains(' ') || value.contains('"') || value.contains('\'') {
            content.push_str(&format!("{}=\"{}\"\n", key, value.replace('"', "\\\"")));
        } else {
            content.push_str(&format!("{}={}\n", key, value));
        }
    }
    std::fs::write(output_path, content)
        .map_err(|e| OspError::VaultError(format!("Cannot write {}: {}", output_path.display(), e)))?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_env_missing_template_returns_err() {
        let vault = super::Vault::open().unwrap();
        let key = [0u8; 32];
        let result = generate_env(
            std::path::Path::new("/nonexistent/.env.osp"),
            &vault,
            &key,
        );
        assert!(result.is_err());
    }

    #[test]
    fn generate_env_plain_pairs_no_osp_uris() {
        let tmp = std::env::temp_dir().join("env-gen-test-plain");
        std::fs::create_dir_all(&tmp).unwrap();
        let template = tmp.join(".env.osp");
        std::fs::write(&template, "# comment\nFOO=bar\nBAZ=qux\n").unwrap();

        let vault = super::Vault::open().unwrap();
        let key = [0u8; 32];
        let pairs = generate_env(&template, &vault, &key).unwrap();
        assert_eq!(pairs.len(), 2);
        assert!(pairs.iter().any(|(k, v)| k == "FOO" && v == "bar"));
        assert!(pairs.iter().any(|(k, v)| k == "BAZ" && v == "qux"));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn write_env_file_creates_file_with_pairs() {
        let tmp = std::env::temp_dir().join("env-gen-test-write");
        std::fs::create_dir_all(&tmp).unwrap();
        let output = tmp.join(".env");
        let pairs = vec![
            ("KEY_ONE".to_string(), "value1".to_string()),
            ("KEY_TWO".to_string(), "value with spaces".to_string()),
        ];
        write_env_file(&output, &pairs).unwrap();
        let content = std::fs::read_to_string(&output).unwrap();
        assert!(content.contains("KEY_ONE=value1"));
        assert!(content.contains("KEY_TWO=\"value with spaces\""));
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
