use std::path::Path;

use super::credentials;
use super::discovery::OspError;
use super::vault::Vault;

/// Parse a .env.osp template and resolve osp:// URIs from the vault.
/// Returns resolved key=value pairs ready to write to .env.
pub fn generate_env(
    template_path: &Path,
    vault: &Vault,
    agent_secret_key: &[u8; 32],
) -> Result<Vec<(String, String)>, OspError> {
    let content = std::fs::read_to_string(template_path)
        .map_err(|e| OspError::VaultError(format!("Cannot read {}: {}", template_path.display(), e)))?;

    let mut result = Vec::new();
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = trimmed.split_once('=') {
            let key = key.trim().to_string();
            let value = value.trim().to_string();
            if value.starts_with("osp://") {
                let resolved = credentials::resolve_osp_uri(&value, vault, agent_secret_key)?;
                result.push((key, resolved));
            } else {
                result.push((key, value));
            }
        }
    }
    Ok(result)
}

/// Write resolved env pairs to a .env file.
pub fn write_env_file(
    output_path: &Path,
    pairs: &[(String, String)],
) -> Result<(), OspError> {
    let mut content = String::new();
    content.push_str("# Generated by better env generate\n");
    content.push_str("# Do not commit this file\n\n");
    for (key, value) in pairs {
        // Quote values that contain spaces or special chars
        if value.contains(' ') || value.contains('"') || value.contains('\'') {
            content.push_str(&format!("{}=\"{}\"\n", key, value.replace('"', "\\\"")));
        } else {
            content.push_str(&format!("{}={}\n", key, value));
        }
    }
    std::fs::write(output_path, content)
        .map_err(|e| OspError::VaultError(format!("Cannot write {}: {}", output_path.display(), e)))?;
    Ok(())
}
